language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    
before_install:
 - chmod +x gradlew
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r moNOpoly *
  - mkdir -p deploy
  - mv moNOpoly.zip deploy/moNOpoly.zip


deploy:
  - provider: s3
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: monopoly-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: Jang-jinwoo/moNOpoly-back #Github 주소
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: monopoly-deploy # S3 버킷
    key: moNOpoly.zip # S3 버킷에 저장된 moNOpoly.zip 파일을 EC2로 배포
    bundle_type: zip
    application: moNOpoly # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: moNOpoly-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: Jang-jinwoo/moNOpoly-back
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - zerone0512@gmail.com 
